# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.15.3

EAPI=8

CRATES="
	adler2@2.0.1
	aes@0.9.0
	aho-corasick@1.1.4
	anstream@1.0.0
	anstyle-parse@1.0.0
	anstyle-query@1.1.5
	anstyle-wincon@3.0.11
	anstyle@1.0.14
	anyhow@1.0.102
	ar_archive_writer@0.5.2
	async-trait@0.1.89
	auto_impl@1.3.0
	autocfg@1.5.0
	bit-set@0.8.0
	bit-vec@0.8.0
	bitflags@1.3.2
	bitflags@2.11.1
	block-buffer@0.10.4
	block-buffer@0.12.0
	bumpalo@3.20.2
	bytes@1.11.1
	bzip2@0.6.1
	cc@1.2.62
	cfg-if@1.0.4
	cipher@0.5.1
	clap@4.6.1
	clap_builder@4.6.0
	clap_derive@4.6.1
	clap_lex@1.1.0
	cmov@0.5.3
	colorchoice@1.0.5
	const-oid@0.10.2
	constant_time_eq@0.4.2
	cpubits@0.1.1
	cpufeatures@0.2.17
	cpufeatures@0.3.0
	crc32fast@1.5.0
	crossbeam-utils@0.8.21
	crypto-common@0.1.7
	crypto-common@0.2.1
	ctutils@0.4.2
	dashmap@5.5.3
	dashmap@6.2.1
	deflate64@0.1.12
	deranged@0.5.8
	digest@0.10.7
	digest@0.11.3
	displaydoc@0.2.5
	equivalent@1.0.2
	errno@0.3.14
	fastrand@2.4.1
	find-msvc-tools@0.1.9
	flate2@1.1.9
	fnv@1.0.7
	foldhash@0.1.5
	form_urlencoded@1.2.2
	futures-channel@0.3.32
	futures-core@0.3.32
	futures-executor@0.3.32
	futures-io@0.3.32
	futures-macro@0.3.32
	futures-sink@0.3.32
	futures-task@0.3.32
	futures-util@0.3.32
	futures@0.3.32
	generic-array@0.14.7
	getrandom@0.3.4
	getrandom@0.4.2
	hashbrown@0.14.5
	hashbrown@0.15.5
	hashbrown@0.17.1
	heck@0.5.0
	hmac@0.13.0
	httparse@1.10.1
	hybrid-array@0.4.12
	icu_collections@2.2.0
	icu_locale_core@2.2.0
	icu_normalizer@2.2.0
	icu_normalizer_data@2.2.0
	icu_properties@2.2.0
	icu_properties_data@2.2.0
	icu_provider@2.2.0
	id-arena@2.3.0
	idna@1.1.0
	idna_adapter@1.2.2
	indexmap@2.14.0
	indoc@2.0.7
	inout@0.2.2
	is_terminal_polyfill@1.70.2
	itoa@1.0.18
	jobserver@0.1.34
	js-sys@0.3.98
	lazy_static@1.5.0
	leb128fmt@0.1.0
	libbz2-rs-sys@0.2.5
	libc@0.2.186
	linux-raw-sys@0.12.1
	litemap@0.8.2
	lock_api@0.4.14
	log@0.4.29
	lsp-types@0.94.1
	lzma-rust2@0.16.2
	matchers@0.2.0
	memchr@2.8.0
	miniz_oxide@0.8.9
	mio@1.2.0
	nu-ansi-term@0.50.3
	num-conv@0.2.1
	num-traits@0.2.19
	object@0.37.3
	once_cell@1.21.4
	once_cell_polyfill@1.70.2
	parking_lot@0.12.5
	parking_lot_core@0.9.12
	pbkdf2@0.13.0
	percent-encoding@2.3.2
	pest@2.8.6
	pest_derive@2.8.6
	pest_generator@2.8.6
	pest_meta@2.8.6
	pin-project-internal@1.1.13
	pin-project-lite@0.2.17
	pin-project@1.1.13
	pkg-config@0.3.33
	potential_utf@0.1.5
	powerfmt@0.2.0
	ppmd-rust@1.4.0
	ppv-lite86@0.2.21
	prettyplease@0.2.37
	proc-macro2@1.0.106
	proptest@1.11.0
	psm@0.1.31
	quick-error@1.2.3
	quick-xml@0.40.1
	quote@1.0.45
	r-efi@5.3.0
	r-efi@6.0.0
	rand@0.9.4
	rand_chacha@0.9.0
	rand_core@0.9.5
	rand_xorshift@0.4.0
	redox_syscall@0.5.18
	regex-automata@0.4.14
	regex-syntax@0.8.10
	ropey@1.6.1
	rustix@1.1.4
	rustversion@1.0.22
	rusty-fork@0.3.1
	same-file@1.0.6
	scopeguard@1.2.0
	semver@1.0.28
	serde@1.0.228
	serde_core@1.0.228
	serde_derive@1.0.228
	serde_json@1.0.150
	serde_repr@0.1.20
	sha1@0.11.0
	sha2@0.10.9
	sharded-slab@0.1.7
	shlex@1.3.0
	signal-hook-registry@1.4.8
	simd-adler32@0.3.9
	slab@0.4.12
	smallvec@1.15.1
	socket2@0.6.3
	stable_deref_trait@1.2.1
	stacker@0.1.24
	str_indices@0.4.4
	strsim@0.11.1
	syn@2.0.117
	sync_wrapper@1.0.2
	synstructure@0.13.2
	tempfile@3.27.0
	test-case-core@3.3.1
	test-case-macros@3.3.1
	test-case@3.3.1
	thiserror-impl@2.0.18
	thiserror@2.0.18
	thread_local@1.1.9
	time-core@0.1.8
	time@0.3.47
	tinystr@0.8.3
	tokio-macros@2.7.0
	tokio-util@0.7.18
	tokio@1.52.3
	tower-layer@0.3.3
	tower-lsp-macros@0.9.0
	tower-lsp@0.20.0
	tower-service@0.3.3
	tower@0.4.13
	tower@0.5.3
	tracing-attributes@0.1.31
	tracing-core@0.1.36
	tracing-log@0.2.0
	tracing-subscriber@0.3.23
	tracing@0.1.44
	typed-path@0.12.3
	typenum@1.20.0
	ucd-trie@0.1.7
	unarray@0.1.4
	unicode-ident@1.0.24
	unicode-xid@0.2.6
	url@2.5.8
	utf8_iter@1.0.4
	utf8parse@0.2.2
	valuable@0.1.1
	version_check@0.9.5
	wait-timeout@0.2.1
	walkdir@2.5.0
	wasi@0.11.1+wasi-snapshot-preview1
	wasip2@1.0.3+wasi-0.2.9
	wasip3@0.4.0+wasi-0.3.0-rc-2026-01-06
	wasm-bindgen-macro-support@0.2.121
	wasm-bindgen-macro@0.2.121
	wasm-bindgen-shared@0.2.121
	wasm-bindgen@0.2.121
	wasm-encoder@0.244.0
	wasm-metadata@0.244.0
	wasmparser@0.244.0
	winapi-util@0.1.11
	windows-link@0.2.1
	windows-sys@0.61.2
	wit-bindgen-core@0.51.0
	wit-bindgen-rust-macro@0.51.0
	wit-bindgen-rust@0.51.0
	wit-bindgen@0.51.0
	wit-bindgen@0.57.1
	wit-component@0.244.0
	wit-parser@0.244.0
	writeable@0.6.3
	yoke-derive@0.8.2
	yoke@0.8.2
	zerocopy-derive@0.8.48
	zerocopy@0.8.48
	zerofrom-derive@0.1.7
	zerofrom@0.1.8
	zeroize@1.8.2
	zerotrie@0.2.4
	zerovec-derive@0.11.3
	zerovec@0.11.6
	zip@8.6.0
	zlib-rs@0.6.3
	zmij@1.0.21
	zopfli@0.8.3
	zstd-safe@7.2.4
	zstd-sys@2.0.16+zstd.1.5.7
	zstd@0.13.3
"

inherit cargo

DESCRIPTION="Rust toolchain for Event-B: parser, static checker, CLI, and language server"
HOMEPAGE="https://github.com/eventb-rossi/rossi"
SRC_URI="
	https://github.com/eventb-rossi/rossi/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
	${CARGO_CRATE_URIS}
"

LICENSE="|| ( Apache-2.0 MIT )"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 Apache-2.0-with-LLVM-exceptions MIT Unicode-3.0 ZLIB
	BZIP2
	|| ( CC0-1.0 MIT-0 )
"
SLOT="0"
KEYWORDS="~amd64"
IUSE="test"
RESTRICT="!test? ( test )"

# These tests guard that the in-repo tree-sitter editor grammar
# (editors/tree-sitter-eventb, a git submodule absent from the release tarball)
# stays in sync with the canonical token tables. They check files this package
# neither builds nor installs, so skip them rather than fetch the submodule.
CARGO_SKIP_TESTS=(
	editor_grammars_are_up_to_date
	generated_nodes_are_listed_in_token_choice
)

DOCS=( README.md )

src_install() {
	# Both binaries come from the single `cargo build` the default src_compile
	# runs; install them from the shared target dir rather than `cargo install`
	# per crate, which would re-run the LTO release build for each.
	dobin "$(cargo_target_dir)"/{rossi,eventb-language-server}

	einstalldocs

	# Example Event-B models for reference.
	docinto examples
	dodoc crates/rossi/examples/*.eventb
}
